### ISSUE TITLE
[EPIC] Support sharing Android "app" module with KMM Templates

### ISSUE THREAD

**Issue by luongvo** [nimblehq/android-templates#506]
## Why

KMM uses the entire Android app module as a presentation layer to build the Android app. There are many of the same setups and features as Android Template's app module. Hence, reusing the app module from Android Templates will help to reduce the maintenance effort a lot.

This EPIC ensures to have necessary POC before proposing to the Android chapter and to do necessary actions to share the "app" module to the KMM Templates.
- All changes will be introduced and applied only on the [template-compose's app module](https://github.com/nimblehq/android-templates/tree/develop/template-compose/app).

## Who Benefits?

Developers

```[tasklist]
### Tasks
- [x] https://github.com/nimblehq/android-templates/issues/512
- [x] https://github.com/nimblehq/android-templates/issues/513
- [x] https://github.com/nimblehq/android-templates/issues/514
- [x] https://github.com/nimblehq/android-templates/issues/515
```
